name: test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build containers
        run: |
          mkdir data
          docker-compose up -d
        env:
          EUSAGE_DATA_DIRECTORY: ./data
          POSTGRES_PASSWORD: password
